CREATE TABLE DIRECTORY (
   ID INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1)
   ,NAME VARCHAR(30) DEFAULT NULL
   ,RIGHTS SMALLINT DEFAULT 509
   ,DIR_ID INT DEFAULT NULL
);

create table MEMBER (
   id INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1)
   ,NAME VARCHAR(30) DEFAULT NULL,
   ,CONTENT BLOB NOT NULL DEFAULT ''
   ,DIR_ID INT DEFAULT NULL
   ,RIGHTS SMALLINT DEFAULT 436
);