CREATE TABLE SHELF (
   ID INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1)
   ,SHELF_NAME VARCHAR(30) DEFAULT NULL
   ,LOCATION CHAR(6) DEFAULT NULL
);

create table BOOK (
   ID INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1)
   ,TITLE VARCHAR(30) DEFAULT NULL
   ,FST_AUTHOR VARCHAR(30) DEFAULT NULL
   ,SHELF_ID INT DEFAULT NULL
   ,PUBL_YEAR INT DEFAULT NULL
);